### ISSUE TITLE
Use a button to execute a command

### ISSUE THREAD

**Issue by sipsorcery** [robotdotnet/DotNetDash#4]
I'm attempting to achieve what I thought would be a straight forward task of using the Smart Dashboard to execute ad-hoc commands in Test mode. I thought it would be straight forward due to a lot of the documentation on the wpilib.screenstepslive.com and comments in the example robot programs alluding to exactly that approach.

To date I am still struggling with that goal due to problems with the various Smart Dashboards. I've tried the default LabView one as well as the C++/Java (the C++ one is actually a Java app so not sure what's going on there) one. In the LabView case I could not get the Command tab to populate at all. In the C++/Java case I could get my command to show up and execute it but NOT in Test mode due to some dashboard layout problems where system controls get put over the top of my command buttons as soon as I activate Test mode (I tried [CD.](https://www.chiefdelphi.com/forums/showthread.php?t=150689) for that one but no luck).

So here I am at DotNetDash. Any my very long winded question is how would I go about using a XAML button to initiate a Command on the roboRio when Test mode is activated?

I have gotten as far as creating a Command.xaml plugin in the DotNetDash.XamlPlugins and that correctly renders when I call SmartDashboard::PutData("Some Command", new SomeCommand()); from my C++ robot code. But I'm now stuck with how I would wire up a button in the Command.xaml plugin to send the execute signal via NetworkTables to the robot program?

**Comment by jkoritzinsky** [comment]
@sipsorcery Sorry I haven't answered this question earlier. I've been extremely busy and this has been a little on the back-burner recently since I'm working on getting the cross-platform UI toolkit to be feature complete enough for use in DotNetDash.

The way to figure out how to do this is to check how a command is triggered in WPILib via NetworkTables (like in the `updateTable` method or something similar to that. You might need to create a C# plugin instead of a XAML plugin.

In the future, I'm going to work on simplifying the C# plugin design so it doesn't require compilation and can be scripted.

**Comment by sipsorcery** [comment]
Yep that's pretty much what I ended up doing.

It's more of an education/documentation situation rather than a code issue which is why I closed it.

**Comment by jkoritzinsky** [comment]
I'm going to leave this open so I remember that this needs to be added as well as that I need to rearchitect the C# plugins.

**Comment by jkoritzinsky** [comment]
This is in the most recent version
